from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from agent.policy_agent import process_policy_request
from utils.trace import get_trace_id

# =======================================
# Router setup
# =======================================
router = APIRouter(
    prefix="/policy-agent",
    tags=["Policy Agent"]
)

# =======================================
# Request / Response Models
# =======================================
class PolicyRequest(BaseModel):
    message: str
    auto_approve: bool = False


class PolicyResponse(BaseModel):
    answer: str
    escalation_required: bool
    department: str | None = None
    email_payload: dict | None = None
    status: str
    trace_id: str
    confidence_score: float
    next_action : str


# =======================================
# HEALTH CHECK API - /policy-agent/health
# =======================================
@router.get("/health", tags=["Health"])
def health_check():
    return {
        "status": "UP",
        "agent": "AI_POLICY_AGENT",
        "trace_id": get_trace_id()
    }


# =======================================
# POST API - /policy-agent/ask
# =======================================
@router.post("/ask", response_model=PolicyResponse)
def handle_policy_request(req: PolicyRequest):
    """
    Receives a policy-related user request.

    trace_id:
    - Generated by middleware
    - Stored in context
    - Accessible via get_trace_id()
    """
    try:
        result = process_policy_request(
            user_input=req.message,
            auto_approve=req.auto_approve
        )

        return result

    except Exception as e:
        raise HTTPException(
            status_code=400,
            detail={
                "error": str(e),
                "trace_id": get_trace_id()
            }
        )
